# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: hgnguyen199.github.io
title: Hannah's Quarantine Guide
author: Hannah Nguyen
description: > #

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
